# Build settings
markdown: kramdown
Conectamos: pretty

lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

url: https://y7kim.github.io
baseurl: ""

# Site settings
title: FreeSoft Solutions
email: contact@freesofts.com
description: "Conectamos personas de una manera más eficiente y productiva"


# Team names, titles and social links
people:
- name: Pedro Gómez Martín
  pic: pedro
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Elena Gonzalez Esteban
  pic: elena
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Eva Casta Auría
  pic: eva
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Alberto Monterroso Barco
  pic: alberto
  position: Chief Technology Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Victor García Martínez
  pic: victor
  position: IT Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210
